apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: my-mariadb-instance
  namespace: default
spec:
  clusterServiceClassExternalName: sacloud-mariadb
  clusterServicePlanExternalName: db-10g
  parameters:
    switch_id: <put-your-value>
    ipaddress: "<put-your-ipaddress>"
    mask_len: <put-your-mask-len>
    default_route: "<put-your-default-route>"
