apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: my-mariadb-instance
  namespace: default
spec:
  clusterServiceClassExternalName: sacloud-mariadb
  clusterServicePlanExternalName: db-10g
  parameters:
    switchID: <your-switch-id>
    ipaddress: "<your-db-private-ip>"
    maskLen: <your-db-mask-len>
    defaultRoute: "<your-db-default-route-ip>"
